// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOT9k1LuMTd-uBIQ_EsLOxSr64W0lsf7Y',
    appId: '1:911078889899:web:67619d2a7accf6763e1aee',
    messagingSenderId: '911078889899',
    projectId: 'chat-3d912',
    authDomain: 'chat-3d912.firebaseapp.com',
    storageBucket: 'chat-3d912.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtK6HQmW9uqaRbqGNqMqMBfv9kNiN4L30',
    appId: '1:911078889899:android:602067d443d761e23e1aee',
    messagingSenderId: '911078889899',
    projectId: 'chat-3d912',
    storageBucket: 'chat-3d912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqUH5Vvd2grg7ETTtKeray9_qs73Apd2k',
    appId: '1:911078889899:ios:3cc2d3cb54d6e4b13e1aee',
    messagingSenderId: '911078889899',
    projectId: 'chat-3d912',
    storageBucket: 'chat-3d912.appspot.com',
    iosClientId: '911078889899-p6cdgrisaaklavho7512vr3oqk7n4en9.apps.googleusercontent.com',
    iosBundleId: 'com.shamilla.flash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqUH5Vvd2grg7ETTtKeray9_qs73Apd2k',
    appId: '1:911078889899:ios:3cc2d3cb54d6e4b13e1aee',
    messagingSenderId: '911078889899',
    projectId: 'chat-3d912',
    storageBucket: 'chat-3d912.appspot.com',
    iosClientId: '911078889899-p6cdgrisaaklavho7512vr3oqk7n4en9.apps.googleusercontent.com',
    iosBundleId: 'com.shamilla.flash',
  );
}
